build-image:
    ansible-playbook -i inventory.ini local build-and-push-image.yaml --ask-become-pass

deploy-image:
    ansible-playbook -i inventory.ini deploy.yaml --ask-become-pass

run-main-playbook:
    ansible-playbook -i inventory.ini main.yaml --ask-become-pass
