build-image:
    bash -c "set -o allexport; source ../.env; set +o allexport; ansible-playbook -i inventory.ini build-and-push-image.yaml --ask-become-pass"

deploy-image:
    bash -c "set -o allexport; source ../.env; set +o allexport; ansible-playbook -i inventory.ini deploy.yaml --ask-become-pass"

run-load-env:
    # Load environment variables from .env
    set -o allexport && source ../.env && set +o allexport

run-main-playbook:
    # Run your Ansible playbook
    bash -c "set -o allexport; source ../.env; set +o allexport; ansible-playbook -i inventory.ini main.yaml --ask-become-pass"

run-all:
    # Build, push, and deploy in sequence
    bash -c "set -o allexport; source ../.env; set +o allexport; ansible-playbook -i inventory.ini main.yaml --ask-become-pass"
